spring:
  datasource:
    platform: h2
    generate-unique-name: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:recommender
    username: sa
    password:
    #https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html
    schema: classpath:schema-h2.sql
    data: classpath:data-h2.sql
    sql-script-encoding: utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
  logging:
    level:
      org.hibernate: DEBUG

  jpa:
    hibernate:
      ddl-auto: update
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true

  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true